"""
Lab 2 - Task 2: Armstrong Number – AI Comparison (Gemini vs GitHub Copilot)
Student: Roger A Raju (Roll No: 2503A52370, Batch: 13)
"""

# ==========================================
# Version 1: Google Gemini (Colab Generated)
# Style: Modular, Mathematical Step-by-Step, Explanatory
# ==========================================
def is_armstrong_gemini(number: int) -> bool:
    """
    Checks if a number is an Armstrong (Narcissistic) number.
    Generated by Google Gemini in Colab using mathematical decomposition.
    """
    if not isinstance(number, int) or number < 0:
        return False
        
    num_str = str(number)
    num_digits = len(num_str)
    
    # Calculate sum of digits raised to the power of number of digits
    total_sum = 0
    for char_digit in num_str:
        total_sum += int(char_digit) ** num_digits
        
    return total_sum == number


# ==========================================
# Version 2: GitHub Copilot Generated
# Style: Pythonic, Concise List Comprehension
# ==========================================
def is_armstrong_copilot(n: int) -> bool:
    """
    Checks if a number is an Armstrong number using concise Pythonic syntax.
    Generated by GitHub Copilot auto-completion.
    """
    return isinstance(n, int) and n >= 0 and sum(int(d) ** len(str(n)) for d in str(n)) == n


def test_armstrong_comparison():
    print("--- Running Test Assertions for Task 2 (Armstrong Number: Gemini vs Copilot) ---")
    
    test_cases = [
        (153, True, "3-digit Armstrong: 1^3 + 5^3 + 3^3 = 153"),
        (370, True, "3-digit Armstrong: 3^3 + 7^3 + 0^3 = 370"),
        (371, True, "3-digit Armstrong: 3^3 + 7^3 + 1^3 = 371"),
        (407, True, "3-digit Armstrong: 4^3 + 0^3 + 7^3 = 407"),
        (1634, True, "4-digit Armstrong: 1^4 + 6^4 + 3^4 + 4^4 = 1634"),
        (9, True, "Single-digit Armstrong: 9^1 = 9"),
        (123, False, "Non-Armstrong number"),
        (500, False, "Non-Armstrong number")
    ]
    
    for num, expected, desc in test_cases:
        res_gemini = is_armstrong_gemini(num)
        res_copilot = is_armstrong_copilot(num)
        assert res_gemini == expected, f"Gemini failed on {num}"
        assert res_copilot == expected, f"Copilot failed on {num}"
        assert res_gemini == res_copilot, f"Discrepancy between Gemini and Copilot on {num}"
        print(f"Assertion Passed: {num} -> Expected: {expected} | Gemini: {res_gemini} | Copilot: {res_copilot} ({desc})")
        
    print("All Armstrong AI Comparison Assertions passed successfully!")


def main():
    print("=== Task 2: Armstrong Number AI Comparison (Gemini vs Copilot) ===")
    print("[AI CAPABILITY] AI Comparison: Gemini emphasizes explanatory modular code; Copilot delivers concise Pythonic one-liners.")
    print("[VERIFICATION] Deterministic Validation: Both models achieved 100% assertion agreement across standard & edge cases.\n")
    test_armstrong_comparison()


if __name__ == "__main__":
    main()
